import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ground,HOUSE,LAND,radius} from '../public/world/math.js';
const source=path=>readFile(new URL('../'+path,import.meta.url),'utf8');
test('workshop footprint rests on land above the sea',()=>{assert.ok(ground(HOUSE.x,HOUSE.z)>18);for(const dx of [-4.5,4.5])for(const dz of [-3.2,3.5])assert.ok(radius(HOUSE.x+dx,HOUSE.z+dz)<1);assert.ok(LAND.rz<LAND.rx);});
test('active scene uses real local Three.js and not a picture/video background',async()=>{const s=await source('public/world/atelier.js');assert.match(s,/new T.WebGLRenderer/);assert.match(s,/createWorkshop/);assert.doesNotMatch(s,/VideoTexture|https?:\/\//);});
test('workshop contains an artisan, actual notes and physical boards',async()=>{const s=(await source('public/world/workshop.js'))+(await source('public/world/workshop-shell.js'));for(const term of ['createArtisan','CanvasTexture','live strategy board','setState','thinking','info.audience','info.channel'])assert.ok(s.includes(term));});
test('workshop updates reflect current local request and error state',async()=>{const s=await source('public/world-controller.js');for(const term of ['latestPlan(t)',"querySelector('.thinking')",'t.error',"t.status==='draft'",'world.setState(workState)'])assert.ok(s.includes(term));});
test('player/game controls are removed from the customer experience',async()=>{const s=await source('public/world-controller.js');assert.match(s,/\[data-world=explore\].*remove/);assert.doesNotMatch(s,/world\.explore\(/);});
test('mobile geometry reduction keeps real meshes and does not downsample desktop previews',async()=>{const s=await source('public/world/atelier.js');assert.match(s,/lightGeometry=mobile/);assert.match(s,/makeMeadow\(scene,materials,lightGeometry\)/);assert.match(s,/prefers-reduced-motion/);});
test('renderer is suspended off the customer routes and disposed correctly',async()=>{const s=await source('public/world/atelier.js');for(const term of ['visibilitychange','webglcontextlost','cancelAnimationFrame','dispose()'])assert.ok(s.includes(term));});
test('only actual human review states create a review stamp',async()=>{const s=(await source('public/world/workshop.js'))+(await source('public/world/workshop-shell.js'));assert.match(s,/stamp.visible=info.stage==='reviewed'\|\|info.stage==='preparing'/);});
