import test from 'node:test';
import assert from 'node:assert/strict';
import { demoReply, validatePlan, validateReply, makeThread, addReply, submitRequest, reviewRequest, approveRequest, requestRevision, versionPlan, escapeHTML, artifactFor, TOOLS } from '../public/domain.js';
import { load, save } from '../public/store.js';
const messages=[{role:'user',text:'쇼핑몰 CS 서비스'},{role:'assistant',text:'고객은 누구인가요?'},{role:'user',text:'작은 쇼핑몰 운영팀'},{role:'assistant',text:'예산은요?'},{role:'user',text:'10만원 안에서'}];
const plan=()=>demoReply(messages).plan;
const ready=()=>{const t=makeThread('첫 고객');addReply(t,demoReply(messages));return t;};
test('first demo response asks one question without generating a plan',()=>{const r=demoReply(messages.slice(0,1));assert.equal(r.plan,null);assert.equal((r.reply.match(/\?/g)||[]).length,1);assert.equal(r.quickReplies.length,3);});
test('uncertain customer is supported',()=>assert.match(demoReply(messages.slice(0,1)).quickReplies[0],/함께/));
test('demo proposal derives the stated budget',()=>assert.match(plan().budget,/100,000/));
test('unknown budget is not fabricated',()=>{const m=structuredClone(messages);m[4].text='아직 몰라요';assert.match(demoReply(m).plan.budget,/미정/);});
test('valid plan receives stable path identifiers',()=>assert.equal(validatePlan(plan()).paths[0].id,'path-1'));
test('unsupported tools are rejected',()=>{const p=plan();p.paths[0].tools=['auto-spam'];assert.throws(()=>validatePlan(p));});
test('empty strategy is rejected',()=>assert.throws(()=>validatePlan({})));
test('plan requires execution paths',()=>{const p=plan();p.paths=[];assert.throws(()=>validatePlan(p));});
test('no more than four tools per path',()=>{const p=plan();p.paths[0].tools=Object.keys(TOOLS);assert.throws(()=>validatePlan(p));});
test('malformed LLM response fails instead of using a demo silently',()=>assert.throws(()=>validateReply({reply:null,plan:plan()})));
test('question about existing plan does not create a new version',()=>{const p=plan();assert.equal(demoReply([...messages,{role:'user',text:'왜 이 방법인가요?'}],p).plan,null);});
test('plan revision can preserve original',()=>{const p=plan();const before=structuredClone(p);demoReply([...messages,{role:'user',text:'무료로 바꿔주세요'}],p);assert.deepEqual(p,before);});
test('new thread starts in draft with no fabricated activity',()=>{const t=makeThread('hello');assert.equal(t.status,'draft');assert.deepEqual(t.artifacts,[]);assert.deepEqual(t.events,[]);});
test('cannot submit without a plan',()=>assert.throws(()=>submitRequest(makeThread('hello'))));
test('submit snapshots the proposal version',()=>{const t=ready();submitRequest(t);assert.equal(t.submittedVersion,1);assert.equal(t.status,'requested');});
test('submitting the same pending version is idempotent',()=>{const t=ready();submitRequest(t);submitRequest(t);assert.equal(t.events.length,1);});
test('later AI drafts do not change a submitted snapshot',()=>{const t=ready();submitRequest(t);const before=structuredClone(versionPlan(t,1));const p=plan();p.title='next draft';addReply(t,{reply:'new',plan:p,quickReplies:[]});assert.equal(t.submittedVersion,1);assert.deepEqual(versionPlan(t,1),before);});
test('stale marketer review is rejected',()=>{const t=ready();submitRequest(t);assert.throws(()=>reviewRequest(t,plan(),'note',9));});
test('review produces a new version, not an overwrite',()=>{const t=ready();submitRequest(t);const p=plan();p.title='review';reviewRequest(t,p,'note',1);assert.equal(t.reviewedVersion,2);assert.notEqual(versionPlan(t,1).title,versionPlan(t,2).title);});
test('cannot approve before marketer review',()=>{const t=ready();submitRequest(t);assert.throws(()=>approveRequest(t));});
test('approval prepares without sending or creating fake results',()=>{const t=ready();submitRequest(t);reviewRequest(t,plan(),'note',1);approveRequest(t);approveRequest(t);assert.equal(t.status,'preparing');assert.equal(t.approvedVersion,2);assert.equal(t.events.length,3);assert.deepEqual(t.artifacts,[]);});
test('revision returns a reviewed proposal to the queue',()=>{const t=ready();submitRequest(t);reviewRequest(t,plan(),'note',1);requestRevision(t,'change');assert.equal(t.status,'requested');assert.equal(t.submittedVersion,2);assert.equal(t.reviewedVersion,null);});
test('revision note is required',()=>{const t=ready();submitRequest(t);reviewRequest(t,plan(),'note',1);assert.throws(()=>requestRevision(t,''));});
test('artifacts identify themselves as templates, not results',()=>{for(const id of Object.keys(TOOLS))assert.match(artifactFor(plan(),id),/실제 조사·발송·게시 결과가 아닙니다/);});
test('HTML output escaping blocks injection',()=>assert.equal(escapeHTML('<img "x">'),'&lt;img &quot;x&quot;&gt;'));
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
test('store round trip preserves version and thread',()=>{const storage=memory(),state={schema:2,threads:[ready()]};save(state,storage);assert.deepEqual(load(storage),state);});
test('corrupt store does not silently erase original data',()=>{const storage={getItem:()=>'{bad',setItem:()=>{throw new Error('must not write');}};assert.throws(()=>load(storage),/원본을 지우지/);});
test('storage quota failure is reported',()=>assert.throws(()=>save({},{setItem:()=>{throw new Error('quota');}}),/저장하지/));
