import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {random,ground,radius,walkable,HOUSE,CAMERA_SHOTS,smooth} from '../public/world/math.js';
test('island generation is deterministic',()=>{const a=random(7),b=random(7);for(let i=0;i<100;i++)assert.equal(a(),b());});
test('random values and camera easing are bounded',()=>{const rand=random();for(let i=0;i<1000;i++){const v=rand();assert.ok(v>=0&&v<1);}assert.equal(smooth(-1),0);assert.equal(smooth(2),1);});
test('terrain is finite, emerges above water and agrees at repeated samples',()=>{for(let x=-24;x<24;x+=2)for(let z=-18;z<18;z+=2){assert.ok(Number.isFinite(ground(x,z)));assert.equal(ground(x,z),ground(x,z));if(radius(x,z)<1)assert.ok(ground(x,z)>2);}});
test('traveler cannot walk through cottage or off the island',()=>{assert.equal(walkable(HOUSE.x,HOUSE.z),false);assert.equal(walkable(70,70),false);assert.equal(walkable(.8,4.9),true);});
test('camera route has an ocean establishing shot and ends near the traveler',()=>{assert.equal(CAMERA_SHOTS.length,5);assert.ok(Math.hypot(CAMERA_SHOTS[0].p[0],CAMERA_SHOTS[0].p[2])>60);assert.ok(CAMERA_SHOTS.at(-1).p[2]<30);});
test('3D uses local, pinned Three.js rather than a CDN or a mock renderer',async()=>{const s=await readFile(new URL('../public/world/island.js',import.meta.url),'utf8');assert.match(s,/vendor\/three.module.js/);assert.match(s,/new T.WebGLRenderer/);assert.doesNotMatch(s,/https?:\/\//);});
test('depth lens uses the real render depth, not CSS backdrop blur',async()=>{const s=await readFile(new URL('../public/world/lens.js',import.meta.url),'utf8');assert.match(s,/new T.DepthTexture/);assert.match(s,/texture2D\(tDepth/);assert.match(s,/uFocus/);});
test('scene observes motion preference, context loss and render disposal',async()=>{const s=await readFile(new URL('../public/world/island.js',import.meta.url),'utf8');for(const term of ['prefers-reduced-motion','webglcontextlost','visibilitychange','dispose()','isTyping'])assert.ok(s.includes(term),term);});
